### ISSUE TITLE
How to deal with different UPOS and XPOS annotations?

### ISSUE THREAD

**Issue by kupietz** [KorAP/KorAP-XML-CoNLL-U#5]
What would be nice options, interface and output without breaking backwards compatibility (only UPOS is considered, now)?
Or do this automatically if both are present and differ?

**Comment by Akron** [comment]
Are you limitting this question to `conllu2korapxml`?

**Comment by kupietz** [comment]
No, it should work both ways and easy round-tripping is one more criterion.

**Comment by Akron** [comment]
But is there a problem with `korapxml2conllu` at all?

**Comment by kupietz** [comment]
Yes, roughly the same problem: It doesn't distinguish between xpos und upos.

**Comment by Akron** [comment]
So, you would like to have parameter arguments to define, what feature name defines upos and what defines xpos?
I suggest `upos=pos` (defaulting to `pos`) and `xpos=pos` (defaulting to `pos` for korapxml2connlu and defaulting to undef for conllu2korapxml). As far as I see, that would only break behaviour for `ctag` in korapxml2connlu, but afaik this was already ill-defined because of features with both parameters.
Btw. what does `unknown++` means here:
https://github.com/KorAP/KorAP-XML-CoNLL-U/blob/f2b0bbaff7e76ff3f43d78a7851b0fca67e877ef/script/korapxml2conllu#L195-L197

**Comment by kupietz** [comment]
I don't quite understand what you propose.  The easiest way to discuss the solution is probably to propose some code, but it's not so urgent, now. In any case, I'd take into account if the respective other value is defined or not and if the values differ or not, and typically upos=pos and xpos=xpos (=x in Krill?).


`unknown` was once used to count words and to make sure that:
https://github.com/KorAP/KorAP-XML-CoNLL-U/blob/f2b0bbaff7e76ff3f43d78a7851b0fca67e877ef/script/korapxml2conllu#L272

However, now, it probably makes not much anymore.
